/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BekuldesRouteImport } from './routes/bekuldes'
import { Route as ForrasokRouteImport } from './routes/forrasok'
import { Route as RolunkRouteImport } from './routes/rolunk'
import { Route as TamogatasRouteImport } from './routes/tamogatas'
import { Route as VisszajelzesRouteImport } from './routes/visszajelzes'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as HirIdRouteImport } from './routes/hir.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BekuldesRoute = BekuldesRouteImport.update({
  id: '/bekuldes',
  path: '/bekuldes',
  getParentRoute: () => rootRouteImport,
} as any)
const ForrasokRoute = ForrasokRouteImport.update({
  id: '/forrasok',
  path: '/forrasok',
  getParentRoute: () => rootRouteImport,
} as any)
const RolunkRoute = RolunkRouteImport.update({
  id: '/rolunk',
  path: '/rolunk',
  getParentRoute: () => rootRouteImport,
} as any)
const TamogatasRoute = TamogatasRouteImport.update({
  id: '/tamogatas',
  path: '/tamogatas',
  getParentRoute: () => rootRouteImport,
} as any)
const VisszajelzesRoute = VisszajelzesRouteImport.update({
  id: '/visszajelzes',
  path: '/visszajelzes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const HirIdRoute = HirIdRouteImport.update({
  id: '/hir/$id',
  path: '/hir/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bekuldes': typeof BekuldesRoute
  '/forrasok': typeof ForrasokRoute
  '/rolunk': typeof RolunkRoute
  '/tamogatas': typeof TamogatasRoute
  '/visszajelzes': typeof VisszajelzesRoute
  '/api/ask': typeof ApiAskRoute
  '/hir/$id': typeof HirIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bekuldes': typeof BekuldesRoute
  '/forrasok': typeof ForrasokRoute
  '/rolunk': typeof RolunkRoute
  '/tamogatas': typeof TamogatasRoute
  '/visszajelzes': typeof VisszajelzesRoute
  '/api/ask': typeof ApiAskRoute
  '/hir/$id': typeof HirIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bekuldes': typeof BekuldesRoute
  '/forrasok': typeof ForrasokRoute
  '/rolunk': typeof RolunkRoute
  '/tamogatas': typeof TamogatasRoute
  '/visszajelzes': typeof VisszajelzesRoute
  '/api/ask': typeof ApiAskRoute
  '/hir/$id': typeof HirIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bekuldes'
    | '/forrasok'
    | '/rolunk'
    | '/tamogatas'
    | '/visszajelzes'
    | '/api/ask'
    | '/hir/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bekuldes'
    | '/forrasok'
    | '/rolunk'
    | '/tamogatas'
    | '/visszajelzes'
    | '/api/ask'
    | '/hir/$id'
  id:
    | '__root__'
    | '/'
    | '/bekuldes'
    | '/forrasok'
    | '/rolunk'
    | '/tamogatas'
    | '/visszajelzes'
    | '/api/ask'
    | '/hir/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BekuldesRoute: typeof BekuldesRoute
  ForrasokRoute: typeof ForrasokRoute
  RolunkRoute: typeof RolunkRoute
  TamogatasRoute: typeof TamogatasRoute
  VisszajelzesRoute: typeof VisszajelzesRoute
  ApiAskRoute: typeof ApiAskRoute
  HirIdRoute: typeof HirIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bekuldes': {
      id: '/bekuldes'
      path: '/bekuldes'
      fullPath: '/bekuldes'
      preLoaderRoute: typeof BekuldesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forrasok': {
      id: '/forrasok'
      path: '/forrasok'
      fullPath: '/forrasok'
      preLoaderRoute: typeof ForrasokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolunk': {
      id: '/rolunk'
      path: '/rolunk'
      fullPath: '/rolunk'
      preLoaderRoute: typeof RolunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tamogatas': {
      id: '/tamogatas'
      path: '/tamogatas'
      fullPath: '/tamogatas'
      preLoaderRoute: typeof TamogatasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visszajelzes': {
      id: '/visszajelzes'
      path: '/visszajelzes'
      fullPath: '/visszajelzes'
      preLoaderRoute: typeof VisszajelzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hir/$id': {
      id: '/hir/$id'
      path: '/hir/$id'
      fullPath: '/hir/$id'
      preLoaderRoute: typeof HirIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BekuldesRoute: BekuldesRoute,
  ForrasokRoute: ForrasokRoute,
  RolunkRoute: RolunkRoute,
  TamogatasRoute: TamogatasRoute,
  VisszajelzesRoute: VisszajelzesRoute,
  ApiAskRoute: ApiAskRoute,
  HirIdRoute: HirIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
